# Creating Secret 
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
data:
  DB_USER: YWRtaW4K
  DB_PWD: cHdzLTAwMXgK

--- 
# Pod with Secrts 
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod 
spec:
  containers:
  - name: nginx-cnt
    image: nginx:latest 
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: db-secret

