apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:                                         # labels applied to SET 
    app: roboshop
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 5
  selector:                                       # This determines which pod should go and attach to teh set
    matchLabels:
      tier: frontend
  template:                                       # labels applied to the created pod 
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx 
        image: nginx:mainline-perl

### Replicaset is not going to support the update of the version from x to y 
### Main job of the replicaset is to ensure the mentioned number of pods are running or not and that's the main goal. 