### Deployment Set with Recreation Strategy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx02-deployment
  labels:
    app: nginx02
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50
  selector:
    matchLabels:
      app: nginx02
  template:
    metadata:
      labels:
        app: nginx02
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:              # port where your container listens
        - containerPort: 80 

--- 
# ClusterIP is a service, that is used for inter-service communication and this cannot be accessed from the internet.
apiVersion: v1
kind: Service
metadata:
  name: nginx02-svc
spec:
  selector:
    app: nginx01
  type: NodePort
  ports:
    - protocol: TCP
      port: 80              # Port where your service listens against
      targetPort: 80        # This is the port where kubernetes service will forward the request to associated pod 
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007